In [1]:
import pandas as pd

In [3]:
def load_data(path):
    df = pd.read_csv(path)
    return df

df = load_data("../data/07-8_seoul_market_sales.csv")

In [4]:
df['상권_구분_코드_명'].unique().tolist()

['발달상권', '전통시장', '골목상권', '관광특구']

In [5]:
df[df['상권_구분_코드_명'].isin(['발달상권', '전통시장', '골목상권', '관광특구'])].head()

,기준_년분기_코드,상권_구분_코드_명,상권_코드_명,서비스_업종_코드_명,당월_매출_금액,당월_매출_건수,주중_매출_금액,주말_매출_금액,남성_매출_금액,여성_매출_금액,연령대_10_매출_금액,연령대_20_매출_금액,연령대_30_매출_금액,연령대_40_매출_금액,연령대_50_매출_금액,연령대_60_이상_매출_금액
0,20254,발달상권,"신촌역(신촌역, 신촌로터리)",스포츠 강습,190574012,563,185879107,4694905,62004846,122818273,1578072,62149177,70583498,12783010,35309971,2419391
1,20254,전통시장,동화동 골목형상점가,미용실,241121913,7596,158201210,82920703,110263603,126565631,689103,17374758,40986830,66989251,63290864,47498428
2,20254,전통시장,노량진중앙시장,커피-음료,143339677,43869,95844027,47495650,84490667,57487331,2121862,42653948,43692418,15772423,24945022,12792323
3,20254,골목상권,신성초등학교,세탁소,7965729,1790,5012268,2953461,5563095,2402634,0,3482559,3099859,774966,511869,96476
4,20254,발달상권,가산디지털단지,한식음식점,38845970041,1458137,34858600092,3987369949,16401281607,9491707466,78552880,4244996087,8066632051,6146656007,4798277628,2557874422

In [6]:
df["서비스_업종_코드_명"].unique()

<ArrowStringArray>
[      '스포츠 강습',          '미용실',        '커피-음료',          '세탁소',
        '한식음식점',           '가방',        '스포츠클럽',       '일반교습학원',
          '편의점',         '일반의류',          '당구장',           '서적',
          '청과상',         '슈퍼마켓',         '일반의원',        '양식음식점',
      '호프-간이주점',         '섬유제품',        '중식음식점',          '화장품',
      '운동/경기용품',          '의약품',        '외국어학원',          '노래방',
        '자동차수리',          '핸드폰',        '피부관리실',         '조명용품',
        '치킨전문점',          '제과점',           '문구',         '반찬가게',
          '네일숍',           '안경',   '컴퓨터및주변장치판매',        '일식음식점',
         '가전제품',        '분식전문점',         '치과의원',         '인테리어',
       '패스트푸드점',         '육류판매',       '전자상거래업',         '의료기기',
           '여관',           '가구',           '화초',         '예술학원',
        '골프연습장',          'PC방',           '완구',           '신발',
         '미곡판매', '자전거 및 기타운송장비',       '시계및귀금속',       '가전제품수리',
          '철물점',        '수산물판매',       '부동산중개업',          '한의원',
        '자동차미용',         '애완동물']
Length: 62, dtype: str

In [7]:
pd.DataFrame(df.groupby("서비스_업종_코드_명")["당월_매출_금액"].sum()).sort_values("당월_매출_금액", ascending=False).head(5)

                  당월_매출_금액
서비스_업종_코드_명
수산물판매        1173768486115
일반의류          912398939719
한식음식점         826313224411
청과상           469853664615
일반의원          440579900528