### 도시 공원 데이터

- 우리도시에 공원이 충분할까?
- 지역마다 어떤 차이가 있은지
- 간단한 질문에서 출발
- 삶의 질, 복지 , 등등,사업 등과 연결이 가능

- 새롭게 알게된 사실 인사이트 insight

In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("../data/city_park.csv")
df.head()
df.isna().sum()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18499 entries, 0 to 18498
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   관리번호          18499 non-null  str
 1   공원명           18499 non-null  str
 2   공원구분          18499 non-null  str
 3   소재지도로명주소      3131 non-null   str
 4   소재지지번주소       18310 non-null  str
 5   위도            18499 non-null  float64
 6   경도            18499 non-null  float64
 7   공원면적          18499 non-null  float64
 8   공원보유시설(운동시설)  5370 non-null   str
 9   공원보유시설(유희시설)  6252 non-null   str
 10  공원보유시설(편익시설)  5110 non-null   str
 11  공원보유시설(교양시설)  548 non-null    str
 12  공원보유시설(기타시설)  2747 non-null   str
 13  지정고시일         15230 non-null  str
 14  관리기관명         17507 non-null  str
 15  전화번호          17526 non-null  str
 16  데이터기준일자       18499 non-null  str
dtypes: float64(3), str(14)
memory usage: 2.4 MB

### 데이터를 정제하기 위해서 조건식을 사용

- 공원면적을 통계로 확인

In [7]:
df.describe()

                 위도            경도          공원면적
count  18499.000000  18499.000000  1.849900e+04
mean      36.502789    127.469601  3.033110e+04
std        1.029747      0.847369  2.133286e+05
min       33.218571    125.433012  0.000000e+00
25%       35.558629    126.864257  1.503000e+03
50%       36.785392    127.104036  2.281800e+03
75%       37.433572    128.082836  1.025750e+04
max       38.491242    137.202661  1.486486e+07

In [ ]:
df['공원면적'].mean()

np.float64(30331.098937942592)

In [9]:
df.columns

Index(['관리번호', '공원명', '공원구분', '소재지도로명주소', '소재지지번주소', '위도', '경도', '공원면적',
       '공원보유시설(운동시설)', '공원보유시설(유희시설)', '공원보유시설(편익시설)', '공원보유시설(교양시설)',
       '공원보유시설(기타시설)', '지정고시일', '관리기관명', '전화번호', '데이터기준일자'],
      dtype='str')

In [12]:
columns = ['공원명','공원구분','공원면적']

clean_df = df[columns]
clean_df
clean_df['큰공원여부'] = clean_df['공원면적'] >= 50_000
clean_df.head()

       공원명   공원구분       공원면적  큰공원여부
0   태종대유원지     기타  1713763.0   True
1    용두산공원   근린공원    70812.0   True
2     월전공원   근린공원    40038.5  False
3  극락어린이공원  어린이공원     1643.3  False
4  서광어린이공원  어린이공원     3067.2  False

### 2. 면적을 기준으로 보고 싶다 -> 정렬 개념
- 큰값부터 정렬
- 작은값부터 정렬

In [13]:
clean_df.sort_values("공원면적", ascending=False)

                  공원명  공원구분        공원면적  큰공원여부
4697   랜드마크시티 1호 체육공원  체육공원  14864860.0   True
6304            옥녀봉공원  근린공원   9320660.0   True
14936         불광산근린공원  근린공원   7404000.0   True
2745         수락산<시공원>    기타   6691885.3   True
8868          모악산도립공원  근린공원   5608490.0   True
...               ...   ...         ...    ...
3626    1호 소공원(진위3지구)   소공원         0.0  False
3628     1호 소공원(장당지구)   소공원         0.0  False
18067           대구대공원  근린공원         0.0  False
3429          율리 근린공원  근린공원         0.0  False
3772          봉남 근린공원  근린공원         0.0  False

[18499 rows x 4 columns]

##### 3. 특정 그룹별로 한번 집계(통계게산)
- groupby
- 공원 종류별 묶어서 개수, 합계, 평균 면적 계산
- 어떤 유형의 공원이 어떤 도시에 많이 있는 지

In [17]:
# 공원면적이 0인 값, 호근 얼마 이하인 값들은 제거 예정
clean_df.groupby("공원구분")["공원면적"].count()
summary=clean_df.groupby("공원구분")["공원면적"].agg(['count','sum',"mean",'median'])
summary.sort_values("count", ascending=False)

        count           sum           mean     median
공원구분
어린이공원    9301  3.000545e+07    3226.045285    1785.00
근린공원     4112  3.898640e+08   94811.291314   24909.50
소공원      3105  8.511675e+06    2741.280167    1137.00
기타        539  2.889889e+07   53615.742356    1117.00
문화공원      483  2.225936e+07   46085.635197    7721.00
수변공원      405  1.307368e+07   32280.692346   11688.20
체육공원      269  3.501785e+07  130177.881784   25562.00
역사공원      204  1.199243e+07   58786.443235   15933.00
묘지공원       39  1.821648e+07  467089.287179  214640.40
기타공원       29  2.142740e+04     738.875862     335.90
도시농업공원      7  3.158591e+06  451227.271429   49805.90
가로공원        3  1.197100e+04    3990.333333    3272.00
주제공원        2  6.257890e+04   31289.450000   31289.45
마을마당        1  5.849000e+02     584.900000     584.90

  - 일반 생활공원: 근린공원, 소공원, 어린이공원, 가로공원, 마을마당
  - 자연형 공원: 수변공원, 도시농업공원
  - 특수목적 공원: 문화공원, 역사공원, 주제공원, 체육공원, 묘지공원
  - 확인 필요: 기타, 기타공원

##### 인사이트
- 어린이공원, 소공원은 개수가 많지만 그키가 작다
- 근린공원은 평균면적이 크다 
- 개수 1위는 어린이공원이지만, 전체면적으로 보면 주 공원은 근린공원이다.



### 4. 교차표 만들기 - pivot_table
- 어떤 두 칼럼(범주) 를 가로, 세로로 교차시켜 요약
- 관리기반 X 공원구분의 평균 면적을 같이 보려고 할 때

In [ ]:
table_df = clean_df.pivot_table(index="공원구분",
                          columns="큰공원여부",
                          values="공원명",
                          aggfunc="count",
                          fill_value=0)
table_df

큰공원여부   False  True
공원구분
가로공원        3      0
근린공원     2869   1243
기타        512     27
기타공원       29      0
도시농업공원      4      3
마을마당        1      0
묘지공원        5     34
문화공원      387     96
소공원      3094     11
수변공원      332     73
어린이공원    9286     15
역사공원      158     46
주제공원        1      1
체육공원      190     79

In [ ]:
table_df = df.pivot_table(index="공원구분",
                          columns="큰공원여부",
                          values="공원명",
                          aggfunc="count",
                          fill_value=0)
table_df

In [25]:
melt_df = table_df.reset_index()
melt_df.columns

Index(['공원구분', False, True], dtype='object', name='큰공원여부')

In [29]:
melt_df = table_df.reset_index().melt(id_vars="공원구분",
                          var_name="큰공원여부",
                            value_name="공원수",
                          )
melt_df

      공원구분  큰공원여부   공원수
0     가로공원  False     3
1     근린공원  False  2869
2       기타  False   512
3     기타공원  False    29
4   도시농업공원  False     4
5     마을마당  False     1
6     묘지공원  False     5
7     문화공원  False   387
8      소공원  False  3094
9     수변공원  False   332
10   어린이공원  False  9286
11    역사공원  False   158
12    주제공원  False     1
13    체육공원  False   190
14    가로공원   True     0
15    근린공원   True  1243
16      기타   True    27
17    기타공원   True     0
18  도시농업공원   True     3
19    마을마당   True     0
20    묘지공원   True    34
21    문화공원   True    96
22     소공원   True    11
23    수변공원   True    73
24   어린이공원   True    15
25    역사공원   True    46
26    주제공원   True     1
27    체육공원   True    79

In [34]:
clean_df['규모'] = clean_df['공원면적'].apply(lambda X: "큰공원" if X >=30_000 else "작은공원")
# 세분화 해본다면
# 50000이상 -> 큰공원
# 30000 ~ 50000 -> 중간공원
# 30000이하 -> 작은 공원

clean_df['규모'] = clean_df['공원면적'].apply(lambda x: "큰공원" if x >=50000 else ("중간공원" if x>=30000 else "작은공원"))
clean_df.head()

       공원명   공원구분       공원면적  큰공원여부    규모
0   태종대유원지     기타  1713763.0   True   큰공원
1    용두산공원   근린공원    70812.0   True   큰공원
2     월전공원   근린공원    40038.5  False  중간공원
3  극락어린이공원  어린이공원     1643.3  False  작은공원
4  서광어린이공원  어린이공원     3067.2  False  작은공원

In [37]:
def cleaned_fuc(x):
    if x >= 50_000:
        return "큰공원"
    elif x>= 30_000:
        return "중간공원"
    else:
        "작은공원"


clean_df['규모'] = clean_df["공원면적"].apply(cleaned_fuc)
clean_df.head()

       공원명   공원구분       공원면적  큰공원여부    규모
0   태종대유원지     기타  1713763.0   True   큰공원
1    용두산공원   근린공원    70812.0   True   큰공원
2     월전공원   근린공원    40038.5  False  중간공원
3  극락어린이공원  어린이공원     1643.3  False   NaN
4  서광어린이공원  어린이공원     3067.2  False   NaN

In [ ]:
clean_df['규모cut'] = pd.cut(clean_df['공원면적'],
                           bins=[0,30_000,50_000,float('inf')],
                           labels=['큰공원','중간공원','작은공원'])