#### 가설검정의 원리
- 눈에 보이는 차이, 우연또는 필연 판단 방법
- 용어
    ex) 귀무가설,
        대립가설,
        유의가설,
        p-value

#### 가설검정을 해야 할 때
- 데이터 두 그룹의 값이 달라보이기는 하는데 그차이가 우연인지 필연인지 구별할 필요가 있을 떄
    -> 스토리텔링에 중요한 요소일 때

### 1. 질문의 시작
- "남성과 여성의 평균 이용건수가 상이한가?"

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

plt.rcParams["font.family"] = "Malgun Gothic"   # 한글 깨짐 방지(윈도우 기본 폰트)
plt.rcParams["axes.unicode_minus"] = False
df = pd.read_csv("../data/07-9_bike_ttareungi.csv")
df.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,202606,1201,1201. 가락시장역 3번 출구,정기권,NaN,30대,123,8750.55,78.97,339960.75,2621
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
2,202606,3928,3928.고척아이파크아파트 106동 앞,일일권,NaN,40대,7,444.12,4.00,17254.05,148
3,202606,102,102. 망원역 1번출구 앞,가족권(2시간),M,~10대,1,181.72,1.64,7060.00,66
4,202606,2265,2265. 이수고가차도 남단,일일권,F,50대,6,660.63,5.96,25665.78,220

In [4]:
df_gender = df.dropna(subset=['성별'])
df_gender.isna().sum()

대여일자       0
대여소번호      0
대여소명       0
대여구분코드     0
성별         0
연령대코드      0
이용건수       0
운동량        2
탄소량        2
이동거리(M)    0
이용시간(분)    0
dtype: int64

In [19]:
male = df_gender[df_gender['성별']=='M']
female = df_gender[df_gender['성별']=='F']

In [ ]:
# male = df_gender[df_gender['대여소번호']==3116
#                  ]
# male

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
795,202606,3116,3116.신촌역 4번출구,일일권,M,~10대,4,612.82,5.64,24315.02,199
4997,202606,3116,3116.신촌역 4번출구,정기권,M,50대,37,2183.44,19.42,83796.47,1639

In [22]:
total_male = df_gender[df_gender['성별']=='M']['이용건수'].sum()
                 
total_male

np.int64(83566)

In [23]:
total_female = df_gender[df_gender['성별']=='F']['이용건수'].sum()
total_female

np.int64(47247)

### 유의미한 차이인지 아닌지 
- 귀무가설 남녀의 전체 이용건수가 같다
- 대립가설 남녀의 이용 건수가 다르다

### p-Value
- p-value : 귀무가설이 맞다고 할 떄, 지금 본거 같은 차이가 우연히 나올때
- 유의수준 : (0.05) 이정도로 드물면 우연이 아니다라고 보겠다는 기준선

In [24]:
from scipy import stats
# t 검정으로 p-value

t, p =  stats.ttest_ind(male, female, equal_var=False)
print(t,"t통계랑")
print(f"{p:4f}", "p-value")

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

- p-value 가 0.05 보다 작으면 -> 차이가 없다라는 귀무가설
- 대립가설
- 남녀 차이는 우연이 아니라 통계적으로 유의미하다

### 내판단이 틀릴 수 있따
- 1종 오류
    - 사실은 차이가 없는데 있따고 잘못 판단 (억울한 판정)
- 2종 오류
    - 사실은 차이가 있는데 없다고 놓친 판단(놓친 판정)
유의수준이 0.05라는 의미는 -> 1종 오류를 5%까지는 감수하겠다라는 약속

### t검정
- 가장 자주 찾는 질문 : 두 그룹의 평균이 다른가?
- 가장 기본적인 판단 기준

- 일표본 :한 그룹의 평균이 특정 기준과 다른가?
    - 예) 평균 이용 시간이 70분과 다른가?
- 독립표폰 : 서로 다른 두 그룹 비교
- 대응표본 : 같은 대상의 두 조건 비교
    - 같은 상권의 주중 vs 주말

### 1. 일표본 t검정 - 기준값과 다른가
- 따릉이 평균 이용 건수가 40건과 다른가?
- 0.05에 가까울 수록 다르다
- 0.05와 멀어 질수록 맞다

In [26]:
t, p = stats.ttest_1samp(df_gender['이용건수'], 40)
print('평균이용건수', df_gender['이용건수'].mean())
print(p)

평균이용건수 41.03293601003764
0.4504400827223802

### 같은 대상의 두 조건
- 상권들의 주중 매출과 주말 매출이 다를까?

### 서로 다른 그룹 비교
- 남성과 여성의 평균 이용시간

In [28]:
df_gender
df.head()

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,202606,1201,1201. 가락시장역 3번 출구,정기권,NaN,30대,123,8750.55,78.97,339960.75,2621
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
2,202606,3928,3928.고척아이파크아파트 106동 앞,일일권,NaN,40대,7,444.12,4.00,17254.05,148
3,202606,102,102. 망원역 1번출구 앞,가족권(2시간),M,~10대,1,181.72,1.64,7060.00,66
4,202606,2265,2265. 이수고가차도 남단,일일권,F,50대,6,660.63,5.96,25665.78,220

In [29]:
df_gender['이용시간(분)/건별'] = (df_gender['이용시간(분)'] / df_gender['이용건수']).round(2)
df.head(3)

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,202606,1201,1201. 가락시장역 3번 출구,정기권,NaN,30대,123,8750.55,78.97,339960.75,2621
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
2,202606,3928,3928.고척아이파크아파트 106동 앞,일일권,NaN,40대,7,444.12,4.00,17254.05,148

In [30]:
male_time = df_gender[df_gender['성별']=='M']['이용시간(분)/건별']
male_time

1        11.53
3        66.00
5         5.88
6        21.12
7        20.27
         ...
4988     23.12
4991     36.36
4995    148.00
4997     44.30
4999     18.29
Name: 이용시간(분)/건별, Length: 1682, dtype: float64

In [31]:
female_time = df_gender[df_gender['성별']=='F']['이용시간(분)/건별']
female_time

4       36.67
10      20.85
12      10.00
15      35.64
27      64.50
        ...
4987    28.97
4990    16.21
4992    24.75
4993    25.67
4998     9.28
Name: 이용시간(분)/건별, Length: 1506, dtype: float64

In [33]:
t, p = stats.ttest_ind(male_time, female_time, equal_var=False)
print(f"남자평균 {male_time.mean():.2f}")
print(f"여자평균 {female_time.mean():.2f}")
print("p-value",p)
# (df_gender['이용시간(분)/건별'], 40)
# print('평균이용건수', df_gender['이용시간(분)/건별'].mean())
# print(p)

남자평균 29.97
여자평균 31.72
p-value 0.11720961663237059